### ISSUE TITLE
linux PROTOC version

### ISSUE THREAD

**Issue by BaMarcy** [rodellison/Unity-Basic-GRPC#1]
Hi, can you tell me what libprotoc version did you use? Thanks.

**Comment by rodellison** [comment]
Has been a while since working with this.. I recall the plugins had to be the specific ones linked (in the readme), i.e. 1.26 for protoc, and unity package 2.26, otherwise there were compilation errors.  Apologies, moved on to Unreal Engine a year or so back so left this out there if others wanted to experiment. Unsure if there are newer versions that work now - but at the time, these specific versions were the only ones.
